create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  slug_url text not null unique,
  name text,
  whatsapp_phone text,
  created_at timestamptz default now()
);

alter table public.businesses enable row level security;

create policy if not exists "Allow public read businesses"
on public.businesses for select
using (true);

create policy if not exists "Allow public insert businesses"
on public.businesses for insert
with check (true);

create policy if not exists "Allow public update businesses"
on public.businesses for update
using (true)
with check (true);
