create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  slug_url text not null unique,
  name text not null,
  whatsapp_phone text not null,
  business_description text,
  created_at timestamptz not null default now()
);

alter table public.businesses add column if not exists owner_id uuid references auth.users(id) on delete cascade;

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name text not null,
  description text,
  price numeric(12, 2),
  duration_minutes integer,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  service_id bigint references public.services(id) on delete set null,
  customer_name text not null,
  customer_phone text,
  requested_date date,
  requested_time time,
  detail text,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists services_business_id_idx on public.services (business_id);
create index if not exists bookings_business_id_created_at_idx on public.bookings (business_id, created_at desc);

alter table public.businesses enable row level security;
alter table public.services enable row level security;
alter table public.bookings enable row level security;

create policy "Public can read businesses"
on public.businesses for select
using (true);

create policy "Owners can insert businesses"
on public.businesses for insert
with check (auth.uid() = owner_id);

create policy "Owners can update businesses"
on public.businesses for update
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists "Owners can read businesses" on public.businesses;
create policy "Owners can read businesses"
on public.businesses for select
using (owner_id = auth.uid());

drop policy if exists "Owners can create businesses" on public.businesses;
create policy "Owners can create businesses"
on public.businesses for insert
with check (owner_id = auth.uid());

create policy "Owners can delete businesses"
on public.businesses for delete
using (auth.uid() = owner_id);

create policy "Public can read active services"
on public.services for select
using (active = true);

drop policy if exists "Owners can manage services" on public.services;
create policy "Owners can manage services"
on public.services for all
using (
  exists (
    select 1 from public.businesses b
    where b.id = business_id and b.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.businesses b
    where b.id = business_id and b.owner_id = auth.uid()
  )
);

drop policy if exists "Public can create bookings" on public.bookings;
create policy "Public can create bookings"
on public.bookings for insert
with check (
  exists (
    select 1 from public.businesses b
    where b.id = business_id
  )
);

drop policy if exists "Owners can read bookings" on public.bookings;
create policy "Owners can read bookings"
on public.bookings for select
using (
  exists (
    select 1 from public.businesses b
    where b.id = business_id and b.owner_id = auth.uid()
  )
);

drop policy if exists "Owners can update bookings" on public.bookings;
create policy "Owners can update bookings"
on public.bookings for update
using (
  exists (
    select 1 from public.businesses b
    where b.id = business_id and b.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.businesses b
    where b.id = business_id and b.owner_id = auth.uid()
  )
);
